# -*- coding: utf-8 -*-
"""Modelcomparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4Ga8rg5O8p8p3hXy839v7C2Lz6Hfrwc
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
df = pd.read_excel('/content/Exercise 15 Regression Trees Strength2.xlsx')

# Features and target
X = df.drop(columns=['Strength2'])
y = df['Strength2']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train traditional ML models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(max_depth=10, random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "XGBoost Regressor": XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6, random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    results.append([name, round(r2, 4), round(rmse, 4)])

from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
import numpy as np

# Scale Target Variable
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))

# Build Advanced ANN Model
model_ann = Sequential([
    Dense(512, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='linear')
])

# Compile model
model_ann.compile(optimizer='adam', loss='mse')

# Early stopping to avoid overfitting
early_stop = EarlyStopping(monitor='loss', patience=15, restore_best_weights=True)

# Train Model
model_ann.fit(X_train_scaled, y_train_scaled, epochs=300, batch_size=64, verbose=1, callbacks=[early_stop])

# Predictions
y_pred_scaled = model_ann.predict(X_test_scaled)
y_pred_ann = scaler_y.inverse_transform(y_pred_scaled)

r2_ann_1 = r2_score(y_test, y_pred_ann)
rmse_ann_1 = np.sqrt(mean_squared_error(y_test, y_pred_ann))

results.append(["ANN", round(r2_ann_1, 4), round(rmse_ann_1, 4)])

print(f"\n ANN R² Score: {r2_ann_1:.4f}")
print(f" ANN RMSE: {rmse_ann_1:.4f}")

# Display results
results_df = pd.DataFrame(results, columns=["Model", "Test R² Score", "Test RMSE"])
print("\nModel Performance Comparison:\n")
print(results_df)